%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: D:\Documents\工作存档\数学建模\2016美赛\模拟\B\巢湖流域不同土地利用类型非点源N,P排放估计结果.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/01/24 10:45:02

%% Import the data
[~, ~, raw] = xlsread('D:\Documents\工作存档\数学建模\2016美赛\模拟\B\巢湖流域不同土地利用类型非点源N,P排放估计结果.xlsx','Sheet1','A2:B11');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,1);
raw = raw(:,2);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
land_type = cellVectors(:,1);
area = data(:,1);

%% Clear temporary variables
clearvars data raw cellVectors;

%% plot pie
pie(area, land_type);
show()
